 steps:
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['test']
  
 - name: maven:3-jdk-8
   entrypoint: mvn
   args: ['package','-Dmaven.test.skip=true']
   
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/quiet-sum-338114/cloud-spanner-build', '--build-arg=JAR_FILE=target/app/finapp.jar', '.']
images: ['gcr.io/quiet-sum-338114/cloud-spanner-build']
